version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: lending-open-position
    container_name: app
    restart: unless-stopped
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:80'
    networks:
      - lending-open-position
networks:
  lending-open-position:
    driver: bridge